# Generated by Django 2.0.13 on 2019-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
