# Generated by Django 2.0.13 on 2019-04-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('skill', models.CharField(max_length=300)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='cv/')),
                ('approve', models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CvCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'catagories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='JobCircular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('post_name', models.CharField(blank=True, max_length=50)),
                ('publication_Date', models.DateField(auto_now_add=True)),
                ('job_type', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=15)),
                ('skill', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('age_limit', models.CharField(blank=True, max_length=10)),
                ('job_nature', models.CharField(max_length=9)),
                ('application_last_date', models.DateField(auto_now_add=True, null=True)),
                ('salary_range', models.CharField(max_length=10)),
                ('approve', models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default='d', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(max_length=1)),
                ('approve', models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default='d', max_length=1)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcv.CvCatagory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcv.CvCatagory'),
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
