# Generated by Django 2.0.13 on 2019-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requested_feedback_cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
                ('approve', models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default='d', max_length=1)),
            ],
        ),
    ]
