# Generated by Django 2.0.13 on 2019-04-07 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0002_requested_feedback_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_cv',
            name='approve',
        ),
        migrations.AddField(
            model_name='requested_feedback_cv',
            name='tour',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
