# Generated by Django 2.0.13 on 2019-04-07 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0003_auto_20190407_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requested_feedback_cv',
            old_name='user',
            new_name='cv_user',
        ),
        migrations.AddField(
            model_name='requested_feedback_cv',
            name='request_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
